### ISSUE TITLE
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)

### ISSUE THREAD

**Issue by ErrorEater** [ConsenSys-archive/ganache#1080]
```
C:\Projects>ganache
bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
ganache v7.0.0-alpha.0 (@ganache/cli: 0.1.1-alpha.0, @ganache/core: 0.1.1-alpha.0)
Starting RPC server
```

How to fix this `bigint` error?

**Comment by davidmurdoch** [comment]
Thanks for trying out the ganache alpha! What node version are you using?

**Comment by ErrorEater** [comment]
> Thanks for trying out the ganache alpha! What node version are you using?

v14.15.5

**Comment by davidmurdoch** [comment]
Ok, thanks. This happens because one of our dependencies (bigint-buffer) runs a compilation step on installation and this can step may fail for a couple of reasons. One of the reasons is that your system might not have the build-tools the library is looking for. You _can_ install these build tools on Windows (see https://www.npmjs.com/package/windows-build-tools), but you don't actually need to as it automatically alls back to a pure JS solution instead. Though I agree... that warning is very annoying.

I don't want users to see this warning or to have to install build tools. I've put this Issue on our list of TODOs for our 7.0.0 stable release; we'll likely fork the bigint-buffer library and pre-build this native binary for all supported systems (Node.js v10-16 on Linux, Windows, and Mac).

**Comment by wiggledom** [comment]
Hello
I already have that same issues in node.js
Please let me know how to fix that issues exactly
Thanks

**Comment by MicaiahReid** [comment]
@Passionist59 what version of node and Ganache are you running? And on what OS?

**Comment by wiggledom** [comment]
I 'm using 18.2.0 version of node
And I don't use Ganache, I 'm using web3.js

**Comment by smacrineanu** [comment]
> I 'm using 18.2.0 version of node And I don't use Ganache, I 'm using web3.js

Same here, this warning is kind of annoying, I am using Ubuntu 20.04 in WSL.

**Comment by davidmurdoch** [comment]
@Passionist59, @smacrineanu This isn't the web3.js repository.
