### ISSUE TITLE
Error at testing contract from mainnet fork BSC

### ISSUE THREAD

**Issue by martudev** [ConsenSys-archive/ganache#1463]
Hello how are you?,

I want to test a mainnet contract from BSC, so i use this command to fork it:
`ganache-cli -h 0.0.0.0 --db /home/username/blockchain-db -f https://bsc-dataseed.binance.org/`

I make the code in python and connect my web3 to the localhost. When i run my code after a second i run the forked command, then my code works. But if i run my code after a minute i run the forked command, then it throws this error:

`web3.exceptions.ContractLogicError: execution reverted: VM Exception while processing transaction: Error: Returned error: missing trie node eddce6194dbef01a156d96c1e04ad30e660d14d3ec3664cdf163d56e87c848ea (path )`

Someone haves any solution for this?
I found in internet this: https://infura.io/docs/ethereum/add-ons/archiveData
I dont know how to change that 128blocks how can i solve this problem?
Thanks!

**Comment by davidmurdoch** [comment]
This happens when the data that ganache needs to access is not available on the binance node you are connecting to. You need to use a different RPC endpoint. There are some suggestions on RPC endpoints that include binance archive data here: https://www.reddit.com/r/binance/comments/mrmqji/free_bsc_archive_node/

**Comment by martuuamengual** [comment]
Hi!, thanks for youre comment. I was testing some others RPC endpoints but i found that my problem is that ganache is not syncing to the mainnet so then, when the contract i use try to get the new info, shows that error. I supose that is the error i have. I explain you, I made a bot for pancakeswap to trade with some strategies, in mainnet the bot works ok. But i want to test others strategies in a localnet or testnet to then implement that in mainnet. I came up with the idea, since apparently with ganache I can't sync, to use those contracts that pancakeswap and the oracle use and update said market values ​​on my localnet, I think that could be a solution to the problem, I don't know if you know a better way to do it. Thank you in advance. Greetings
