### ISSUE TITLE
Get revert message from eth_sendTransaction

### ISSUE THREAD

**Issue by 0xGorilla** [ConsenSys-archive/ganache#1531]
After sending a transaction that should revert via `eth_sendTransaction` and asking fort the `TransactionReceipt`, we do get `status: 0` but not the revert reason.

Is there any way to get the revert reason from the transaction?

**Comment by wei3erHase** [comment]
implementation in #1529

**Comment by davidmurdoch** [comment]
The _standard way_ is to reissue the transaction with `eth_call`, but due to [this bug](https://github.com/trufflesuite/ganache/issues/1496) you'll have to enable the `chain.legacyInstamine` flag for it to work. You may want to use a package like https://github.com/authereum/eth-revert-reason to make it a bit easier. This big will be fixed before we launch to ganache v7 to stable.

The _non-standard_ way is to enable both `chain.legacyInstamine` and `miner.legacyInstamine` modes. This will cause `eth_sendTransaction` to return a JSON-RPC `error` with a `reason` property containing the reason as `UTF-8` (if decoding is possible), otherwise it will be encoded in the `message` property.

---

We think the `eth_call` to get the rejection process is not adequate, and it can't work in every situation as in certain cases a transaction will only "revert" if transactions that come before it in the same block change state in a specific way. It is possible that `eth_call` cannot replicate the conditions of the original transaction, which may result in a different execution outcome! This is a shortcoming of the JSON-RPC interface and we hope to introduce an EIP to provide better `revert` visibility (or just implement existing solutions we aren't yet aware of! If you know of any, let us know!).

_note: there _is_ another way that Ganache doesn't support yet: `debug_traceTransaction` has a `returnValue` that will contain the revert reason (or the actual return value). Issue: https://github.com/trufflesuite/ganache/issues/1536_

**Comment by 0xGorilla** [comment]
I will try this and reopen the issue if there is any problem, thanks for the great answer!
