### ISSUE TITLE
installed ganache-cli  but after running ganache-cli it's not showing options

### ISSUE THREAD

**Issue by ghost** [ConsenSys-archive/ganache#2243]
I have done this is linux

**Comment by davidmurdoch** [comment]
Which version of node? What do you see when you run the command (you absolutely should NOT see options)?

Try `npm uninstall ganache-cli -g && npm install ganache -g && ganache --help` this will install the latest version and show you all options.

**Comment by ghost** [comment]
> 
i installed it using "yarn global add ganache-cli", it has got installed but it's not showing anything after running "ganache-cli --version" or "ganache --version". The version of node  is v14.18.2.

**Comment by davidmurdoch** [comment]
Did you try what I asked above?

**Comment by ghost** [comment]
yes that is giving following error

npm WARN checkPermissions Missing write access to /usr/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, access '/usr/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yash/.npm/_logs/2022-01-30T17_20_27_489Z-debug.log

**Comment by davidmurdoch** [comment]
Looks like you've used `sudo` to install something globally before. You probably shouldn't be using sudo with npm or yarn.

I know it sounds extreme, but if you've used sudo in order to install npm packages and don't understand the ramifications of doing so (it allows the package author, or any of the authors of dependencies that package relies on to do anything everything they desire with your system; they could install backdoors or even update your bios if they wanted to). You may want to consider formatting your hard drive, resetting your bios, and reinstalling your operating system if you've made a habit of doing this.

Using sudo with the global flag(-g) also changes your npm folder's permissions, which causes issues like you are seeing above. If you don't want to follow my suggestion to reset your system, npm has an article on how you can try to fix npm's permissions: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally .

**Comment by ghost** [comment]
okay will consider your suggestion, and thank you so much for responding.
