### ISSUE TITLE
Cannot specify start block on BSC network

### ISSUE THREAD

**Issue by Ataye** [ConsenSys-archive/ganache#2781]
When I fork the BSC mainnet and specify a start block, I get the following error (yes, this is PowerShell):

```
PS C:\Users\james> ganache -f https://bsc-dataseed.binance.org@16520058 -m MNEMONIC-BIP39-STYLE -u 0xdde420cbb3794ebd8ffc3ac69f9c78e5d1411870
ganache v7.0.3 (@ganache/cli: 0.1.4, @ganache/core: 0.1.4)
Starting RPC server
Error: connect ENETUNREACH 0.252.19.122:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1161:16) {
  errno: -4062,
  code: 'ENETUNREACH',
  syscall: 'connect',
  address: '0.252.19.122',
  port: 443
}
```

But runs fine without the @16520058.

If I use the following command, I get the error:

```
PS C:\Users\james> ganache -f https://bsc-dataseed.binance.org -m MNEMONIC-BIP39-STYLE -u 0xdde420cbb3794ebd8ffc3ac69f9c78e5d1411870 --fork blocknumber=16520058
ganache v7.0.3 (@ganache/cli: 0.1.4, @ganache/core: 0.1.4)
Forking `provider` must be EIP-1193 compatible
```

So, I take it you cannot specify a start block when forking the BSC network (or rather, a non Ethereum network)?

cheers

**Comment by MicaiahReid** [comment]
Hi @Ataye, thanks taking the time to open this issue.
 
It looks like there are a few issues here. First, for some reason Ganache isn't parsing the `@blockNumber` in the fork url.

In your second attempt, you are using `--fork blocknumber=16520058` instead of `--fork.blockNumber=16520058`, so Ganache thinks you are specifying `blocknumber` as the fork network. 

If you fix the startup command to be:
```console
ganache -f https://bsc-dataseed.binance.org -m MNEMONIC-BIP39-STYLE -u 0xdde420cbb3794ebd8ffc3ac69f9c78e5d1411870 --fork.blockNumber=16520058
```
you get a step closer, but you'll still get this strange error: `CodedError: empty resp`. This happens when Ganache attempts to get the nonce of each of the accounts it made from the fork. For some reason BSC is returning this error. Regardless, Ganache probably shouldn't crash.

If you start up Ganache without any accounts, you can fork at a specific block. From there you'd have to unlock the account manually. So your startup command would be:
```console
ganache -f https://bsc-dataseed.binance.org --fork.blockNumber=16520058 --accounts 0
```
This will get you forked at the right block. Then, add and unlock the account using the `evm_addAccount` and `personal_unlockAccount` RPC methods:
```JavaScript
const address = "0xdde420cbb3794ebd8ffc3ac69f9c78e5d1411870";
const passphrase = "passphrase"
const result = await provider.send("evm_addAccount", [address, passphrase] );
const isUnlocked = await provider.send("personal_unlockAccount", [address, passphrase] );
```

We will look into fixes for the two issues, but hopefully this will get you on the right track.

**Comment by Ataye** [comment]
Hello,

Thanks for looking into this.  I originally specified fork.blocknumber but I get Unknown Argument so thought I was doing it wrong:

```
PS C:\Users\james> ganache -f https://bsc-dataseed.binance.org -m MNEMONIC-BIP39-STYLE --fork.blocknumber 16520058
Unknown argument: fork.blocknumber
PS C:\Users\james> ganache -f https://bsc-dataseed.binance.org --fork.blocknumber 16520058
Unknown argument: fork.blocknumber
PS C:\Users\james> ganache -f https://bsc-dataseed.binance.org --fork.blocknumber 16520058 --accounts 0
Unknown argument: fork.blocknumber
```

Then I realised it is case sensitive after seeing your command, I missed the N: --fork.blockNumber :(

I can live without the unlocked account being specified on the command line, so I'll unlock using RPC.

So that's got me going from a specific block, thanks very much for your quick assist :)

**Comment by fainashalts** [comment]
@Ataye it sounds like your issue is resolved, thanks so much for bringing it up and for following up. I'm going to close this for issue maintenance but please feel free to open a new issue if something new comes up!
