### ISSUE TITLE
ganache-cli global installation failed - permission denied

### ISSUE THREAD

**Issue by abstractumx** [ConsenSys-archive/ganache#3011]
Hello!

i am trying to install 
```
$ npm install ganache --global
```
but i have the following issue:
```
abstractum@ubuntu:~$ npm install ganache --global
npm ERR! code EACCES
npm ERR! syscall mkdir
npm ERR! path /usr/local/lib/node_modules
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'
npm ERR!  [Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'mkdir',
npm ERR!   path: '/usr/local/lib/node_modules'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

```
Should I install ganache using root profile? Is not possible to use a non root user? There is a possibility to authorize only this user  for the installation whiteout using root user?

Thank you

**Comment by davidmurdoch** [comment]
Looks like you may have used sudo to install something globally before. You probably shouldn't be using sudo with npm or yarn.

I know it sounds extreme, but if you've used sudo in order to install npm packages and don't understand the ramifications of doing so (it allows the package author, or any of the authors of dependencies that package relies on to do anything everything they desire with your system; they could install backdoors or even update your bios and install rootkits if they wanted to). You may want to consider formatting your hard drive, resetting your bios, and reinstalling your operating system, especially if you've made a habit of doing this.

Using sudo with the global flag(-g) also changes your npm folder's permissions, which could cause issues like you are seeing above. If you don't want to follow my suggestion to reset your system, npm has an article on how you can try to fix npm's permissions: https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally .
