### ISSUE TITLE
ganache script disabled on windows

### ISSUE THREAD

**Issue by HassanSayyed** [ConsenSys-archive/ganache#3171]
After Installing ganache using npm

>  **npm install ganache --global**

When I try to access **ganache** I receive the following error message due to restriction 

> ganache : File C:\Users\LENOVO\AppData\Roaming\npm\ganache.ps1 cannot be loaded because running scripts is disabled on this 
> system. For more
> information, see about_Execution_Policies at [https:/go.microsoft.com/fwlink/?LinkID=135170](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2).
> At line:1 char:1
> + ganache                                                                                                                               more 
> + ~~~~~~~
>     + CategoryInfo          : SecurityError: (:) [], PSSecurityException
>     + FullyQualifiedErrorId : UnauthorizedAccess

**Comment by tenthirtyone** [comment]
Hello @HassanSayyed 

Thank you for reporting this. The `ganache: [path]\ganache.ps1 cannot be loaded because running scripts is disabled on this system.` is a known npm issue and I can help you resolve it. 

When `npm` installs ganache on Windows the `ganache.ps1` file is created. Windows PowerShell will run this script when the `ganache` command is invoked on the PowerShell command line. As a feature of Windows, PowerShell will abide the Execution Policy settings you shared [in your link ](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-7.2). By default, Windows will set script execution to `Restricted` and this is why users will see the error you encountered. It's important to note, this is a function of Windows and not something Ganache controls directly.

The execution policy isn't a security system that restricts user actions. For example, users can easily bypass a policy by typing the script contents at the command line when they cannot run a script. Instead, the execution policy helps users to set basic rules and prevents them from violating them unintentionally. 

Here are several options that should work for you if you are running Windows 10.

### Option 1: Change the PowerShell Execution Policy
1. In PowerShell, run `Get-ExecutionPolicy -List`

Expected: 
You should see output similar to the following:

```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       Undefined
```
2. Run `set-executionpolicy remotesigned`
3. Select 'A' for accept all
4. Re-run `Get-ExecutionPolicy -List`

Expected: 
You should see output similar to the following:

```
        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy       Undefined
   UserPolicy       Undefined
      Process       Undefined
  CurrentUser       Undefined
 LocalMachine       RemoteSigned
```

You will now be able to run the `ganache` command from PowerShell without encountering the ExecutionPolicy error. This will also allow you to run other `npm` packages that have command line components. 

If you do not wish to change the Execution Policy, you can try the following options,

### Option 2: Use `ganache.cmd`
1. Run `ganache.cmd` 

The .ps1 script is a small file that performs a few system checks before executing this command. Running `ganache.cmd` === running `ganache`, it just bypasses the `.ps1` file, and the ExecutionPolicy check.

### Option 3: Use the Windows Command Prompt instead of PowerShell
1. From the Windows start menu, run `cmd`
2. In the Command Prompt run `ganache`

Expected:
This should start Ganache for you.

### Option 4: Use npx
1. You can run Ganache using `npx ganache` and `npx` will pull down ganache and run an instance in the shell and you will always have the latest version of ganache available.

### Option 5: Delete the .ps1 file
PowerShell will fallback on the `.cmd` file when running `ganache`.

Give these a try and let me know how it goes and if we can help with anything else.

**Comment by HassanSayyed** [comment]
### Resolved ✔
you was right it was an npm error, Unfortunately the Options you mentioned didn't work. but the problem was solved using [yarn](https://yarnpkg.com/)  

### Solution  using yarn

1. Make sure to uninstall [ganache ](https://github.com/trufflesuite/ganache)from npm  (in case added before using npm)

- run `npm uninstall ganache-cli & npm uninstall ganache`
- from `C:\Users\%username%\AppData\Roaming\npm` delete ganache files 

3. Install yarn `npm install --global yarn` and make sure the directory `~\Yarn\bin\;` is added to the PATH in the [Environment Variables](https://docs.oracle.com/en/database/oracle/machine-learning/oml4r/1.5.1/oread/creating-and-modifying-environment-variables-on-windows.html#GUID-DD6F9982-60D5-48F6-8270-A27EC53807D0)
4. Run `yarn global add ganache`
5. Restart your command line

**Comment by davidmurdoch** [comment]
@HassanSayyed Take care when using `yarn`, as the resulting code you get from yarn will differ depending on _when_ you install it, as it does not respect published lock files like `npm` does; when installed via yarn the dependencies ganache requires may be different than the dependencies we used when originally tested then published ganache.
