### ISSUE TITLE
Sending future nonce transaction in eager mode causes Ganache to hang

### ISSUE THREAD

**Issue by MicaiahReid** [ConsenSys-archive/ganache#4165]
If a transaction is sent with a future nonce while in eager mining mode, Ganache hangs indefinitely and never returns a response for the transaction.

This happens the blockchain's [`queueTransaction` function](https://github.com/trufflesuite/ganache/blob/b816de218202e3f10182c61de9bae505b3c42710/src/chains/ethereum/ethereum/src/blockchain.ts#L1039-L1072). A future nonce transaction will return `false` for `isExecutable`, yet the code path still leads to awaiting `transaction.once("finalized")`, which won't happen until the nonce gap is filled.

**Comment by itsdevcoffee** [comment]
Does this PR resolve #2509 as well?

**Comment by SvenMeyer** [comment]
Even worse, Metamask hangs as well and never comes back, just showing the spinner ...
```
RPC Listening on 127.0.0.1:7545
eth_blockNumber
eth_getCode
eth_getTransactionCount
eth_blockNumber
eth_sendRawTransaction
Transaction "0x829eaabd43c7c53d759ea704cfffeaa020535f84c6e31db584e7561937e8888b" has a too-high nonce; this transaction has been added to the pool, and will be processed when its nonce is reached. See https://github.com/trufflesuite/ganache/issues/4165 for more information.
eth_blockNumber
eth_blockNumber
```

**Comment by etsraphael** [comment]
Do we finally have a solution for this? I'm still having it.

**Comment by davidmurdoch** [comment]
It isn't hanging. When future-nonce transactions that are sent to Ganache running in eager mining mode appear to hang indefinitely, rather than being mined or rejected. This is expected behavior in eager mode, as Ganache does not return the hash until after it is mined. To help alleviate the confusion we now log a message about the status of these kinds of transactions.
